language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lugomes/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lugomes/react-test npm run test

after_success:
    # Build prod versions of the images
    - docker build -t lugomes/multi-client ./client
    - docker build -t lugomes/multi-nginx ./nginx
    - docker build -t lugomes/multi-server ./server
    - docker build -t lugomes/multi-worker ./worker
    # Log in to Docker CLI using env vars included in Travis CI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to Docker Hub
    - docker push lugomes/multi-client
    - docker push lugomes/multi-nginx
    - docker push lugomes/multi-server
    - docker push lugomes/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-west-2"
    app: multi-docker
    env: Multi-Docker-env
    bucket_name: "elasticbeanstalk-us-east-2-789677611139"
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY